name=eeprom-m95256
version=0.1.0
author=Aaron Kimball
maintainer=Aaron Kimball <akimball83@gmail.com>
sentence=M95256-series EEPROM driver.
paragraph=This library provides a class to easily communicate with M95256-series SPI EEPROM ICs.
category=Data Storage
url=https://github.com/kimballa/eeprom-m95256
architectures=*
includes=eeprom-m95256.h

